[categories]
Food = ["swiggy", "zomato", "restaurant", "cafe", "dominos", "foods", "polar bear", "dlv", "red chilly", "pancakes", "bewitched", "foodking", "mega mart", "vending brothers", "blinkit", "ADITYAFOODMANAGEME", "J.V.SHETTYMEGAMART", "ADITYAFOODMANAGEMENTSERVICESPVTLTD", "ShreeGajalaxmiSnacksBITS"]
Groceries = ["bigbasket", "zepto", "grocery", "amul"]
Transport = ["uber", "ola", "metro", "rapido", "fuel", "petrol"]
Shopping = ["amazon", "flipkart", "myntra"]
Bills = ["electricity", "recharge", "airtel", "jio", "water"]
Entertainment = ["netflix", "spotify", "movie", "bookmyshow", "FanCode"]
Health = ["pharmacy", "hospital", "doctor", "apollo"]
Housing = ["stanzaliving", "LGLaundryLounge"]
Travel = ["ixigo", "travenues", "dudhsagar tours"]
Outing = ["DUDHSAGARTOURSANDTRAVELSPVTLTDPG"]

[parser]
credit_keywords = ["refund", "cashback", "received", "reversal"]