[categories]
Food = ["swiggy", "zomato", "restaurant", "cafe", "dominos", "foods", "polar bear", "dlv", "red chilly", "pancakes", "bewitched", "foodking", "mega mart", "vending brothers", "blinkit", "ADITYAFOODMANAGEME", "J.V.SHETTYMEGAMART", "ADITYAFOODMANAGEMENTSERVICESPVTLTD", "ShreeGajalaxmiSnacksBITS", "CTRLXTECHNOLOGIESPRIVATELIMITED", "VendingBrothersPvtLtd", "BurgerKing", "MCDONALDS", "CALIFORNIABURRITO", "MSJVSHETTYMEGAMART"]
Groceries = ["bigbasket", "zepto", "grocery", "amul", "OPENMART"]
Transport = ["uber", "ola", "metro", "rapido", "fuel", "petrol", "BMTC"]
Shopping = ["amazon", "flipkart", "myntra"]
Bills = ["electricity", "recharge", "airtel", "jio", "water"]
Entertainment = ["netflix", "spotify", "movie", "bookmyshow", "FanCode", "PVRINOXLimited"]
Fitness = ["PlayArena"]
Health = ["pharmacy", "hospital", "doctor", "apollo", "Healthians"]
Housing = ["stanzaliving", "LGLaundryLounge", "RK LaundrySpot"]
Travel = ["ixigo", "travenues", "dudhsagar tours"]
Outing = ["DUDHSAGARTOURSANDTRAVELSPVTLTDPG", "LOCOBEARCOUNTER2", "TRUFFLES", "NANDHANAPALACE"]
Investing = ["MUTUALFUNDSNCL", "GROWWINVESTTECHPVTLTD"]
Hosting = ["HOSTINGERPTELTD"]

[parser]
credit_keywords = ["refund", "cashback", "received", "reversal"]